#!/usr/bin/env bash
# install_n8n.sh - Provision self-hosted n8n on the AppServer node.
# Idempotent. Called from manifest.jps during provisioning, but also safe to
# run stand-alone on an existing box.
#
# Inputs (env vars, all optional unless noted):
#   N8N_DOMAIN         FQDN nginx serves the UI on (e.g. n8n.<env>.jelastic...)
#                      REQUIRED - the manifest passes 'n8n.${env.domain}'.
#   N8N_PORT           External port for the nginx vhost (default 5679).
#   N8N_ALLOWED_IPS    Comma-separated CIDR list for the nginx allow/deny block.
#                      Empty == no allowlist (UI reachable from anywhere) -
#                      the script logs a warning and writes a placeholder.
#   GEMINI_API_KEY     Written to /etc/n8n/n8n.env so the monitor workflow
#                      can call Gemini via the HTTP Request node.
#   MONITOR_SCHEDULE   Cron expression for the monitor workflow trigger.
#                      Default "0 */4 * * *". Surfaced as N8N_MONITOR_SCHEDULE
#                      in the env file.
#   ALERT_EMAIL        Recipient for HIGH/CRITICAL findings.
#   REPO_BASE_URL      Where to fetch sibling files from. Defaults to the
#                      ProxiBlue/HostingEnvironment main branch.

set -euo pipefail

DATA_DIR="/var/lib/n8n"
CONFIG_DIR="/etc/n8n"
N8N_USER="n8n"
N8N_GROUP="n8n"
NGINX_VHOST="/etc/nginx/conf.d/n8n.conf"
SERVICE_FILE="/etc/systemd/system/n8n.service"
SNAPSHOT_BIN="/usr/local/bin/n8n-server-snapshot.sh"
SUDOERS_FILE="/etc/sudoers.d/n8n"
WORKFLOWS_DROP="$DATA_DIR/workflows-pending"

REPO_BASE_URL="${REPO_BASE_URL:-https://raw.githubusercontent.com/ProxiBlue/HostingEnvironment/main/configs/n8n}"
N8N_DOMAIN="${N8N_DOMAIN:?N8N_DOMAIN must be set (e.g. n8n.<env>.example.com)}"
N8N_PORT="${N8N_PORT:-5679}"
N8N_ALLOWED_IPS="${N8N_ALLOWED_IPS:-}"
GEMINI_API_KEY="${GEMINI_API_KEY:-}"
MONITOR_SCHEDULE="${MONITOR_SCHEDULE:-0 */4 * * *}"
ALERT_EMAIL="${ALERT_EMAIL:-}"

log() { echo "[install_n8n] $*"; }

require_root() {
  if [ "$(id -u)" -ne 0 ]; then echo "must run as root" >&2; exit 1; fi
}

require_node() {
  if ! command -v node >/dev/null 2>&1; then
    echo "node is required (>=18.17). The Jelastic InstallCPYumPackages step installs Node.js 20; if you are running this stand-alone, install Node.js first." >&2
    exit 1
  fi
  local major
  major="$(node -p 'process.versions.node.split(".")[0]')"
  if [ "${major:-0}" -lt 18 ]; then
    echo "node $major detected; n8n requires >=18.17" >&2
    exit 1
  fi
}

create_user() {
  if ! getent group "$N8N_GROUP" >/dev/null; then
    groupadd --system "$N8N_GROUP"
  fi
  if ! getent passwd "$N8N_USER" >/dev/null; then
    useradd --system --gid "$N8N_GROUP" --home-dir "$DATA_DIR" \
            --shell /sbin/nologin "$N8N_USER"
  fi
}

create_dirs() {
  install -d -m 0750 -o "$N8N_USER" -g "$N8N_GROUP" "$DATA_DIR"
  install -d -m 0750 -o "$N8N_USER" -g "$N8N_GROUP" "$WORKFLOWS_DROP"
  install -d -m 0750 -o root        -g "$N8N_GROUP" "$CONFIG_DIR"
}

install_n8n_pkg() {
  log "installing n8n via npm (this takes a few minutes - large dep tree)"
  # --omit=dev cuts install size considerably; n8n recommends global install.
  npm install -g --omit=dev n8n@latest
}

write_env_file() {
  log "writing $CONFIG_DIR/n8n.env"
  # Public protocol: HTTP for the initial install. Re-issuing Let's Encrypt
  # for n8n.<domain> via the Jelastic SSL addon switches this to HTTPS.
  local protocol="http"
  local hostname_fqdn
  hostname_fqdn="$(hostname -f 2>/dev/null || hostname)"

  umask 027
  cat > "$CONFIG_DIR/n8n.env" <<EOF
# Generated by install_n8n.sh - safe to edit, then: systemctl restart n8n

# n8n binds to localhost only; nginx terminates the public port and proxies in.
N8N_HOST=127.0.0.1
N8N_PORT=5678
N8N_LISTEN_ADDRESS=127.0.0.1

# Public URL n8n advertises (webhook absolute URLs etc.)
N8N_PROTOCOL=$protocol
WEBHOOK_URL=$protocol://$N8N_DOMAIN:$N8N_PORT/
N8N_EDITOR_BASE_URL=$protocol://$N8N_DOMAIN:$N8N_PORT/

# Trust X-Forwarded-* from the local nginx hop.
N8N_PROXY_HOPS=1

# SQLite (default backend). Made explicit for clarity.
DB_TYPE=sqlite
DB_SQLITE_DATABASE=$DATA_DIR/database.sqlite

N8N_USER_FOLDER=$DATA_DIR
N8N_LOG_LEVEL=info
N8N_LOG_OUTPUT=file
N8N_LOG_FILE_LOCATION=/var/log/n8n.log
N8N_DIAGNOSTICS_ENABLED=false
N8N_VERSION_NOTIFICATIONS_ENABLED=true

# Surfaced to imported workflows via {{ \$env.* }}
GEMINI_API_KEY=$GEMINI_API_KEY
N8N_MONITOR_SCHEDULE=$MONITOR_SCHEDULE
ALERT_EMAIL=$ALERT_EMAIL
SERVER_HOSTNAME=$hostname_fqdn
EOF
  chown root:"$N8N_GROUP" "$CONFIG_DIR/n8n.env"
  chmod 0640 "$CONFIG_DIR/n8n.env"

  # Pre-create the log file so the unprivileged daemon can write to it.
  touch /var/log/n8n.log
  chown "$N8N_USER":"$N8N_GROUP" /var/log/n8n.log
  chmod 0640 /var/log/n8n.log
}

install_snapshot_helper() {
  log "installing $SNAPSHOT_BIN (root-owned data collector)"
  curl -fsSL "$REPO_BASE_URL/n8n-server-snapshot.sh" -o "$SNAPSHOT_BIN"
  chown root:root "$SNAPSHOT_BIN"
  chmod 0755 "$SNAPSHOT_BIN"

  # Allow the n8n daemon user to invoke ONLY this script via sudo, so the
  # workflow can read root-only logs without n8n itself running as root.
  cat > "$SUDOERS_FILE" <<EOF
# n8n daemon - read-only data collection for monitoring workflow
$N8N_USER ALL=(root) NOPASSWD: $SNAPSHOT_BIN
EOF
  chmod 0440 "$SUDOERS_FILE"
  visudo -cf "$SUDOERS_FILE" >/dev/null
}

install_default_workflow() {
  log "fetching default monitoring workflow JSON"
  curl -fsSL "$REPO_BASE_URL/workflows/server-monitor.json" \
       -o "$WORKFLOWS_DROP/server-monitor.json"
  chown -R "$N8N_USER":"$N8N_GROUP" "$WORKFLOWS_DROP"
  chmod 0640 "$WORKFLOWS_DROP/server-monitor.json"
}

write_service() {
  log "writing systemd unit"
  curl -fsSL "$REPO_BASE_URL/n8n.service" -o "$SERVICE_FILE"
  chmod 0644 "$SERVICE_FILE"
  systemctl daemon-reload
}

write_nginx_vhost() {
  log "writing $NGINX_VHOST"
  curl -fsSL "$REPO_BASE_URL/nginx-n8n.conf.template" -o "${NGINX_VHOST}.tpl"

  # Build the allow/deny block from the CIDR list. Empty list -> placeholder
  # comment so nginx still parses; we warn loudly above.
  local allow_block=""
  if [ -n "$N8N_ALLOWED_IPS" ]; then
    while IFS= read -r cidr; do
      cidr="$(echo "$cidr" | xargs)"
      [ -z "$cidr" ] && continue
      allow_block+="    allow $cidr;\n"
    done < <(echo "$N8N_ALLOWED_IPS" | tr ',' '\n')
    allow_block+="    deny all;"
  else
    log "WARNING: N8N_ALLOWED_IPS empty - n8n UI will be reachable from any source IP. Edit $NGINX_VHOST and add allow/deny rules before relying on this."
    allow_block="    # WARNING: no allowlist configured - add 'allow <cidr>;' lines and a trailing 'deny all;' before exposing this UI"
  fi

  sed -e "s|__N8N_DOMAIN__|$N8N_DOMAIN|g" \
      -e "s|__N8N_PORT__|$N8N_PORT|g" \
      "${NGINX_VHOST}.tpl" > "$NGINX_VHOST"

  # Multiline replacement is awkward with sed; do it in python.
  python3 - "$NGINX_VHOST" "$allow_block" <<'PY'
import sys, pathlib
path = pathlib.Path(sys.argv[1])
block = sys.argv[2].replace('\\n', '\n')
text = path.read_text()
path.write_text(text.replace('__ALLOW_BLOCK__', block))
PY
  rm -f "${NGINX_VHOST}.tpl"

  if nginx -t >/dev/null 2>&1; then
    systemctl reload nginx 2>/dev/null || systemctl restart nginx
  else
    echo "[install_n8n] ERROR: nginx config invalid after writing $NGINX_VHOST" >&2
    nginx -t || true
    return 1
  fi
}

start_service() {
  systemctl enable n8n.service
  systemctl restart n8n.service
}

import_default_workflow() {
  # n8n needs an owner account before workflows can be activated, so this
  # may be a no-op until the user finishes the first-login setup. The JSON
  # sits on disk in $WORKFLOWS_DROP either way, ready for "Import from File".
  if sudo -u "$N8N_USER" /usr/bin/n8n import:workflow --separate \
       --input="$WORKFLOWS_DROP/server-monitor.json" 2>/dev/null; then
    log "default workflow imported"
  else
    log "default workflow not auto-imported (no owner account yet) - import via UI from $WORKFLOWS_DROP/server-monitor.json after first login"
  fi
}

main() {
  require_root
  require_node
  create_user
  create_dirs
  install_n8n_pkg
  write_env_file
  install_snapshot_helper
  install_default_workflow
  write_service
  write_nginx_vhost
  start_service
  import_default_workflow
  log "install complete. UI: http://$N8N_DOMAIN:$N8N_PORT/  (create owner account on first visit)"
}

main "$@"
