[nginx-magento-admin]
enabled = true
filter = nginx-magento-admin
logpath = /var/log/nginx/access.log
maxretry = 5
findtime = 300
bantime = 3600
action = iptables-multiport[name=nginx-magento-admin, port="http,https"]
