[nginx-catalogsearch-params]
enabled = true
filter = nginx-catalogsearch-params
logpath = /var/log/nginx/access.log
maxretry = 1
findtime = 60
bantime = 3600
ignoreip = 127.0.0.1/8 ::1
action = iptables-multiport[name=cs-params, port="http,https"]
