[supervisord]
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid
nodaemon=true

[program:opensearch]
command=/usr/share/opensearch/bin/opensearch
process_name=%(program_name)%
user=opensearch
directory=/usr/share/opensearch/
autostart=true
autorestart=true
priority=999
startsecs=1
startretries=3
stdout_logfile=/var/log/opensearch/opensearch.log
stderr_logfile=/var/log/opensearch/opensearch.log

