#!/usr/bin/env bash
# install_monitor.sh - Provisioning installer for the AI server monitor.
# Called from manifest.jps during new-server build, but also safe to run
# stand-alone on a fresh box. Idempotent.
#
# Environment variables (optional):
#   GEMINI_API_KEY     - written into /etc/server-monitor/config.yaml
#   SERVER_TYPE        - magento | drupal | both (default: magento)
#   MONITOR_SCHEDULE   - cron expression (default: "0 */4 * * *")
#   ALERT_EMAIL        - alert recipient address
#   REPO_BASE_URL      - where to fetch agent files from
#                        (default: ProxiBlue/HostingEnvironment main branch)

set -euo pipefail

INSTALL_DIR="/opt/server-monitor"
CONFIG_DIR="/etc/server-monitor"
LOG_FILE="/var/log/server-monitor.log"
CACHE_DIR="/var/lib/server-monitor"
CRON_FILE="/etc/cron.d/server-monitor"
REPO_BASE_URL="${REPO_BASE_URL:-https://raw.githubusercontent.com/ProxiBlue/HostingEnvironment/main/configs/ai-monitor}"

log() { echo "[install_monitor] $*"; }

require_root() {
  if [ "$(id -u)" -ne 0 ]; then
    echo "must run as root" >&2; exit 1
  fi
}

detect_pkg_manager() {
  if command -v dnf >/dev/null 2>&1; then echo dnf
  elif command -v yum >/dev/null 2>&1; then echo yum
  elif command -v apt-get >/dev/null 2>&1; then echo apt
  else echo "unsupported" >&2; exit 1
  fi
}

install_system_deps() {
  local pm; pm="$(detect_pkg_manager)"
  log "installing system deps via $pm"
  case "$pm" in
    dnf|yum)
      # AlmaLinux/RHEL 9: default python3 is 3.9 - too old for crewai (needs 3.10+).
      # Use python3.11 from AppStream. mailx was retired; s-nail provides /usr/bin/mail.
      $pm install -y python3.11 python3.11-pip python3.11-devel gcc s-nail || {
        log "python3.11 install failed, trying python3.12"
        $pm install -y python3.12 python3.12-pip python3.12-devel gcc s-nail
      }
      ;;
    apt)
      DEBIAN_FRONTEND=noninteractive apt-get update -y
      DEBIAN_FRONTEND=noninteractive apt-get install -y \
          python3 python3-pip python3-venv mailutils curl gcc
      ;;
  esac
}

pick_python() {
  # Need python >= 3.10 for crewai. Prefer newest available.
  local cand
  for cand in python3.12 python3.11 python3.10 python3; do
    if command -v "$cand" >/dev/null 2>&1; then
      local ver
      ver="$("$cand" -c 'import sys;print(sys.version_info.major*100+sys.version_info.minor)')"
      if [ "${ver:-0}" -ge 310 ]; then echo "$cand"; return 0; fi
    fi
  done
  echo "[install_monitor] ERROR: no python >= 3.10 found (need it for crewai)" >&2
  return 1
}

create_dirs() {
  install -d -m 0755 "$INSTALL_DIR"
  install -d -m 0750 "$CONFIG_DIR"
  install -d -m 0750 "$CACHE_DIR"
  touch "$LOG_FILE"; chmod 0640 "$LOG_FILE"
}

fetch_agent_files() {
  log "fetching agent files from $REPO_BASE_URL"
  for f in tools.py monitor_agent.py config.yaml.example; do
    curl -fsSL "$REPO_BASE_URL/$f" -o "$INSTALL_DIR/$f"
  done
  chmod 0644 "$INSTALL_DIR"/*.py
}

build_venv() {
  local py
  py="$(pick_python)"
  log "building virtualenv at $INSTALL_DIR/venv using $py"
  "$py" -m venv "$INSTALL_DIR/venv"
  # shellcheck disable=SC1091
  "$INSTALL_DIR/venv/bin/pip" install --no-cache-dir --upgrade pip wheel
  # crewai bundles litellm; litellm talks to Gemini directly via the gemini/ prefix,
  # so we don't need google-generativeai as a separate dep.
  "$INSTALL_DIR/venv/bin/pip" install --no-cache-dir \
      "crewai>=0.80,<1" \
      "pyyaml>=6" \
      "croniter>=2"
}

write_config() {
  if [ -f "$CONFIG_DIR/config.yaml" ]; then
    log "preserving existing $CONFIG_DIR/config.yaml"
    return
  fi
  log "writing $CONFIG_DIR/config.yaml"
  cp "$INSTALL_DIR/config.yaml.example" "$CONFIG_DIR/config.yaml"
  local key="${GEMINI_API_KEY:-}"
  local stype="${SERVER_TYPE:-magento}"
  local sched="${MONITOR_SCHEDULE:-0 */4 * * *}"
  local email="${ALERT_EMAIL:-}"
  python3 - "$CONFIG_DIR/config.yaml" "$key" "$stype" "$sched" "$email" <<'PY'
import sys, yaml
path, key, stype, sched, email = sys.argv[1:6]
with open(path) as f: cfg = yaml.safe_load(f)
if key: cfg["gemini_api_key"] = key
cfg["server_type"] = stype
cfg["schedule"] = sched
if email:
    cfg["alert_email"] = email
with open(path, "w") as f: yaml.safe_dump(cfg, f, sort_keys=False)
PY
  chmod 0640 "$CONFIG_DIR/config.yaml"
}

write_cron() {
  local sched
  sched="$(python3 -c 'import yaml,sys;print(yaml.safe_load(open("/etc/server-monitor/config.yaml")).get("schedule","0 */4 * * *"))')"
  log "writing $CRON_FILE (schedule: $sched)"
  cat > "$CRON_FILE" <<EOF
# AI server monitor - generated by install_monitor.sh
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
$sched root $INSTALL_DIR/venv/bin/python $INSTALL_DIR/monitor_agent.py >> /var/log/server-monitor-cron.log 2>&1
EOF
  chmod 0644 "$CRON_FILE"
  systemctl restart crond 2>/dev/null || systemctl restart cron 2>/dev/null || true
}

self_test() {
  log "running --dry-run as smoke test"
  if "$INSTALL_DIR/venv/bin/python" "$INSTALL_DIR/monitor_agent.py" --dry-run >/dev/null; then
    log "dry-run OK"
  else
    log "dry-run FAILED"; return 1
  fi
  log "running --health-check"
  "$INSTALL_DIR/venv/bin/python" "$INSTALL_DIR/monitor_agent.py" --health-check || true
}

main() {
  require_root
  install_system_deps
  create_dirs
  fetch_agent_files
  build_venv
  write_config
  write_cron
  self_test
  log "install complete. Edit $CONFIG_DIR/config.yaml to set gemini_api_key if not provided yet."
}

main "$@"
