#!/usr/bin/env bash
# update_monitor.sh - Refresh agent code on an existing server.
# Preserves /etc/server-monitor/config.yaml. Re-runs pip install to pick up
# any new dependencies. Refreshes the cron entry from the current config.

set -euo pipefail

INSTALL_DIR="/opt/server-monitor"
CONFIG_DIR="/etc/server-monitor"
CRON_FILE="/etc/cron.d/server-monitor"
REPO_BASE_URL="${REPO_BASE_URL:-https://raw.githubusercontent.com/ProxiBlue/HostingEnvironment/main/configs/ai-monitor}"

log() { echo "[update_monitor] $*"; }

if [ "$(id -u)" -ne 0 ]; then
  echo "must run as root" >&2; exit 1
fi

if [ ! -d "$INSTALL_DIR" ]; then
  echo "$INSTALL_DIR not found - run install_monitor.sh first" >&2; exit 1
fi

log "fetching latest agent files"
for f in tools.py monitor_agent.py config.yaml.example; do
  curl -fsSL "$REPO_BASE_URL/$f" -o "$INSTALL_DIR/$f"
done
chmod 0644 "$INSTALL_DIR"/*.py

log "refreshing pip dependencies"
"$INSTALL_DIR/venv/bin/pip" install --quiet --upgrade \
    "crewai>=0.80,<1" \
    "google-generativeai>=0.7" \
    "litellm>=1.50" \
    "pyyaml>=6" \
    "croniter>=2"

if [ ! -f "$CONFIG_DIR/config.yaml" ]; then
  log "no config.yaml found, copying template (you must edit it)"
  install -d -m 0750 "$CONFIG_DIR"
  cp "$INSTALL_DIR/config.yaml.example" "$CONFIG_DIR/config.yaml"
  chmod 0640 "$CONFIG_DIR/config.yaml"
fi

sched="$(python3 -c 'import yaml;print(yaml.safe_load(open("/etc/server-monitor/config.yaml")).get("schedule","0 */4 * * *"))')"
log "rewriting $CRON_FILE (schedule: $sched)"
cat > "$CRON_FILE" <<EOF
# AI server monitor - regenerated by update_monitor.sh
SHELL=/bin/bash
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
$sched root $INSTALL_DIR/venv/bin/python $INSTALL_DIR/monitor_agent.py >> /var/log/server-monitor-cron.log 2>&1
EOF
chmod 0644 "$CRON_FILE"
systemctl restart crond 2>/dev/null || systemctl restart cron 2>/dev/null || true

log "verifying with --dry-run"
"$INSTALL_DIR/venv/bin/python" "$INSTALL_DIR/monitor_agent.py" --dry-run >/dev/null && log "OK"

log "update complete"
